// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khltrofwauubanidvdjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobHRyb2Z3YXV1YmFuaWR2ZGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTY1ODUsImV4cCI6MjA2OTczMjU4NX0.yV0ELUVC3SrxHlodbuvwdlDR7TVAXoEU4IqU4suvoHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});